[env]
_.file = ".env"

[tasks.build]
run = "go build ."

[tasks.dev]
run = "air"

[tasks.fmt]
description = "Format Go files"
run = "go fmt ./..."

[tasks.db_apply]
description = "Apply up database migrations"
run = "goose -dir sql/schema postgres $DB_URL up"

[tasks.db_revert]
description = "Apply down database migrations"
run = "goose -dir sql/schema postgres $DB_URL down"

[tasks.db_generate]
description = "Generate bindings for SQL queries"
run = "sqlc generate"

[tools]
"go:github.com/air-verse/air" = "latest"
"go:github.com/pressly/goose/v3/cmd/goose" = "latest"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"
